# This is the main configuration for the plugin
# debug value can be true or false. When debug is true, the application prints more in detail log messages
debug: false
# Version number of the application do not change this
version: 2.0

enabled-worlds:
  - world1
  - world2

messages:
  prefix: "&7[&6VTE&7] &r"
  noPermission: "&cYou do not have permission to do this"
  configReloaded: "&aConfig reloaded"
  disabledWorld: "&cThis world is disabled"
  playerOnly: "&cThis command can only be run by a player."
  noBlockInRange: "&cNo block in range to spawn villager."
  noTradePermission: "&cYou do not have permission to trade with this villager."
  notManagedVillager: "&cThis is not a managed villager."
  enterPermissionPrompt: "&eEnter the permission to trade with this villager (type 'none' to clear):"
  permissionCleared: "&aTrade permission cleared."
  permissionSet: "&aPermission set to {0}"
  enterNamePrompt: "&eEnter new name (mm:/mini: for MiniMessage, 'none' to clear, 'cancel' to abort):"
  nameCancelled: "&7Name change cancelled."
  nameCleared: "&aVillager name cleared."
  nameUpdated: "&aVillager name updated."
  villagerDeleted: "&aVillager deleted."