# This is the main configuration for the plugin
# Debug level (0-3): 0 = Severe only, 1 = Warn and above, 2 = Info and above, 3 = Debug and above
debug: 1
# Version number of the application do not change this
version: 3.1

settings:
  command-aliases:
    vte:
      - villagertradeedit
      - villagertrade
      - vtrade
      - vedit

enabled-worlds:
  - world1
  - world2

messages:
  prefix: "&7[&6VTE&7] &r"
  noPermission: "&cYou do not have permission to do this"
  configReloaded: "&aConfig reloaded"
  disabledWorld: "&cThis world is disabled"
  playerOnly: "&cThis command can only be run by a player."
  noBlockInRange: "&cNo block in range to spawn villager."
  noTradePermission: "&cYou do not have permission to trade with this villager."
  notManagedVillager: "&cThis is not a managed villager."
  enterPermissionPrompt: "&eEnter the permission to trade with this villager (type 'none' to clear):"
  permissionCleared: "&aTrade permission cleared."
  permissionSet: "&aPermission set to {0}"
  enterNamePrompt: "&eEnter new name (mm:/mini: for MiniMessage, 'none' to clear, 'cancel' to abort):"
  nameCancelled: "&7Name change cancelled."
  nameCleared: "&aVillager name cleared."
  nameUpdated: "&aVillager name updated."
  villagerDeleted: "&aVillager deleted."