name: Build VillagerTradeEdit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout VillagerTradeEdit
      uses: actions/checkout@v4

    - name: Checkout YskLib
      uses: actions/checkout@v4
      with:
        repository: YusakiDev/YskLib
        path: YskLib

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and install YskLib
      run: |
        cd YskLib
        mvn clean install -DskipTests
        cd ..

    - name: Build VillagerTradeEdit with build number
      run: mvn clean package -DskipTests -Dbuild.number.formatted=-b${{ github.run_number }}

    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        cp target/VillagerTradeEdit-*-b*.jar artifacts/
        cp YskLib/target/YskLib-*-b*.jar artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VillagerTradeEdit
        path: artifacts/*.jar
        compression-level: 0
