name: Build VillagerTradeEdit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout VillagerTradeEdit
      uses: actions/checkout@v4

    - name: Checkout YskLib
      uses: actions/checkout@v4
      with:
        repository: YusakiDev/YskLib
        path: YskLib

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and install YskLib
      run: |
        cd YskLib
        mvn clean install -DskipTests
        cd ..

    - name: Build VillagerTradeEdit
      run: mvn clean package -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VillagerTradeEdit
        path: target/VillagerTradeEdit-*.jar

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: target/VillagerTradeEdit-*.jar
